# Generated by Django 4.1.7 on 2023-03-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='remember_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
